version: "3.8"

services:

  mysql:
    image: mysql:8
    container_name: task-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./Task.Manager/Task.Manager  
    container_name: task-backend
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/taskdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  frontend:
    build: ./frontend  
    container_name: task-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data: